
export let phrasalVerbs=[
  {name:"cut down on",description:["reduce"]},
  {name:"fall apart",description:["fail to succeed","break up", "feel awful"]},
  {name:"do without",description:["get by"]},
  {name:"feel for",description:["symphasize"]},
  {name:"drop in",description:["go to someone without  appointment"]},
  {name:"fall out",description:["to fall out of something","to argue with someone without result", "devastate"]},
  {name:"figure out",description:["discover"]},
  {name:"get round",description:["to do something that you have intended to do for a long time (with to)","to recover (without to)","deceive somebody (with object)","persuade someone using charm (with object)","deal successfully with problem","travel around"]},
  {name:"take after",description:["to resemble somebody"]},
  {name:"let down",description:["to dissapoint someone"]},
  {name:"hand down",description:["pass something on to a younger person or a successor","announce something, especially a judgement or sentence, formally or publicly"]},
  {name:"break down",description:["stop working","mental ___"]},
  {name:"fall through",description:["go ahead(about project)"]},
  {name:"look back on",description:["nostalgia"]},
  {name:"look out for",description:["to be sure that a person doesnt get hurt"]},
  {name:"look after",description:["take care of somebody"]},
  {name:"look to",description:["expect that someone will provide something that you want (+ object)"]},
  {name:"come into",description:["inherit something"]},
  {name:"come up with",description:["think or suggest smth"]},
  {name:"go over",description:["examine or discuss in detail"]},
  {name:"go with",description:["match"]},
  {name:"look up on",description:["respect someone"]},
  {name:"look down on",description:["despise"]},
  {name:"go down",description:["to move down to a lower level or place","to reach or go as far as","BE REDUCED","to be remembered or recorded in a particular way","BE RECEIVED","to lose or be defeated","to be put in prison","stop working","happen(about crime)"]},
  {name:"put off",description:["postpone"]},
  {name:"get together",description:["gather with others"]},
  {name:"put up with",description:["tolerate"]},
  {name:"bring about",description:["to make something happen"]},
  {name:"draw on",description:["to use inf or knowledge"]},
  {name:"flare up",description:["when violece/pain/infection gets worse"]},
  {name:"put in for",description:["make official request to do smth"]},
  {name:"fall into",description:["to start doing smth without intending to do it","to be devided in parts","to go to some state"]},
  {name:"put up to",description:["to encourage someone to do smth wrong(object in the middle)"]},
  {name:"go in for",description:["enjoy smth","compete","study something(for law example)"]},
  {name:"drift off",description:["to gradually start to sleep","to go own world"]},
  {name:"put through",description:["make someone experince smth bad(object in the middle)","to pay for someone to study at school, etc.(object in the middle)","connect a person using a phone to another person(object in the middle)"]},
  {name:"bring in",description:["introduce law,product","make money","to ask someone do a particular work(with object in the middle)"]},
  {name:"pull in",description:["move in that direction and stop there(about vehicle)","attract (for example clients)"]},
  {name:"come off",description:["to happen as planned","to be suscessful without expectation","stop using particular medicine","give a particular impression"]},
  {name:"make up for",description:["to compensate smth damaged,lost with smth good"]},
  {name:"go for",description:["choose smth","try to achieve","sell for particular ammount of money","try to hurt physicly"]},
  {name:"get off",description:["disembark"]},
  {name:"set off",description:["cause a series of events","to cause a loud noise/explosion(bomb/alarm)","start a journey"]},
  {name:"see off",description:["to say goodbuy to person who is leaving(object in the middle)"]},
  {name:"stop off",description:["to visit some place for a short time during journey"]},
  {name:"take off",description:["undress","launch","spend time off work"]},
  {name:"carry out",description:["complete something that you have been told or said you would do","do a task"]},
  {name:'catch on',description:["become popular"]},
  {name:"call for",description:["need/require"]},
  {name:"fall back on",description:["to use something for help because no other choice is available"]},
  {name:"get out of",description:["avoid smth(with an excuse)","stop habit","leave something"]},
  {name:"keep at",description:["persist with something","try to do smth better(with effort)"]},
  {name:"pull off",description:["to drive off road","succeed"]},
  {name:"call off",description:["cancel an event","order something to stop attacking"]},
  {name:"pony up",description:["spend money"]},
  {name:"pull down",description:[]}

]
